import type { CollectionConfig } from 'payload'

/**
 * Media collection.
 *
 * Storage: Vercel Blob (configured via plugin in payload.config.ts).
 *
 * Also stores song masters and stems (`Songs.masterAudio`, stem `audioFile`)
 * via `relationTo: 'media'`. Audio MIME types are whitelisted; `imageSizes`
 * only run for images.
 *
 * Optimization workflow:
 * - The original master file is uploaded as-is (no top-level `formatOptions`),
 *   so 3000x3000 album-art masters are preserved at full fidelity for
 *   downloads.
 * - At upload time, sharp generates a set of optimized derivatives
 *   (`sizes.thumbnail`, `sizes.card`, `sizes.feature`, `sizes.feature_avif`)
 *   in WebP/AVIF. The frontend reads `resource.sizes[name].url` via the
 *   `displaySize` prop on the `Media` / `ImageMedia` components.
 *
 * Backfill: existing uploads can be regenerated by hitting
 * `/api/admin/regenerate-media-sizes` while authenticated as an admin.
 */
export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  folders: true,
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: false,
    },
  ],
  upload: {
    disableLocalStorage: true,
    mimeTypes: [
      // Images & video (cover art, promos)
      'image/png',
      'image/jpeg',
      'image/webp',
      'image/avif',
      'image/svg+xml',
      'image/gif',
      'video/mp4',
      'video/webm',
      'video/quicktime',
      // Audio — Songs.masterAudio and stems use relationTo: 'media'
      'audio/mpeg',
      'audio/mp3',
      'audio/wav',
      'audio/x-wav',
      'audio/wave',
      'audio/flac',
      'audio/x-flac',
      'audio/aac',
      'audio/aiff',
      'audio/x-aiff',
      'audio/ogg',
      'audio/mp4',
    ],
    imageSizes: [
      {
        name: 'thumbnail',
        width: 400,
        height: 400,
        position: 'centre',
        formatOptions: { format: 'webp', options: { quality: 78 } },
      },
      {
        name: 'card',
        width: 800,
        height: 800,
        position: 'centre',
        formatOptions: { format: 'webp', options: { quality: 80 } },
      },
      {
        name: 'feature',
        width: 1600,
        height: 1600,
        position: 'centre',
        formatOptions: { format: 'webp', options: { quality: 82 } },
      },
      // AVIF only at the largest size — encoding is CPU-expensive at upload
      // time and the byte savings only become meaningful at larger dimensions.
      {
        name: 'feature_avif',
        width: 1600,
        height: 1600,
        position: 'centre',
        formatOptions: { format: 'avif', options: { quality: 55 } },
      },
    ],
  },
}

