/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    'mailing-list': MailingList;
    media: Media;
    playlists: Playlist;
    presaves: Presave;
    releases: Release;
    songs: Song;
    'gated-content': GatedContent;
    tags: Tag;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    songs: {
      relatedReleases: 'releases';
      inPlaylists: 'playlists';
      linkedGatedContent: 'gated-content';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'mailing-list': MailingListSelect<false> | MailingListSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    presaves: PresavesSelect<false> | PresavesSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    songs: SongsSelect<false> | SongsSelect<true>;
    'gated-content': GatedContentSelect<false> | GatedContentSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncAudioTags: TaskSyncAudioTags;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature_avif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  username: string;
  /**
   * Controls how your name appears to others on the site, in the forum, and in email communications.
   */
  displayNameFormat:
    | 'firstName'
    | 'lastName'
    | 'fullName'
    | 'username'
    | 'rank_firstName'
    | 'rank_lastName'
    | 'rank_fullName'
    | 'rank_username';
  /**
   * Auto-computed from your display name format preference above.
   */
  displayName?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * Your favorite TSM track, shown on your public profile.
   */
  favoriteSong?: (number | null) | Song;
  zipCode?: number | null;
  /**
   * Private. Used for age demographics only.
   */
  birthdate?: string | null;
  /**
   * Private. Used for aggregate demographics only.
   */
  gender?: ('female' | 'male' | 'non_binary' | 'other' | 'prefer_not_to_say') | null;
  /**
   * Preferred site color theme. Leave empty to follow the featured theme.
   */
  themePreference?: ('dark' | 'light' | 'interstellar' | 'kelly_come_home' | 'nebula' | 'distress') | null;
  /**
   * Control which emails and alerts you receive.
   */
  notificationSettings?: {
    newsletter?: boolean | null;
    productUpdates?: boolean | null;
    accountActivity?: boolean | null;
  };
  role: 'admin' | 'user';
  crewRank: 'ensign' | 'lieutenant' | 'commander' | 'captain' | 'admiral';
  /**
   * Used to link this account to Stripe payments.
   */
  stripeCustomerId?: string | null;
  /**
   * Indicates if the user has linked their YouTube account.
   */
  youtubeConnected?: boolean | null;
  googleAccessToken?: string | null;
  googleRefreshToken?: string | null;
  googleTokenExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  /**
   * Exact song name in title case. Drives the TIT2 (title) frame written to the audio file. Parenthetical version qualifiers like "(Acoustic)" or "(Demo)" are OK; do NOT include "feat. X" — guest artists go in Featured Artists in the sidebar.
   */
  title: string;
  /**
   * Auto-synced from the related Release.
   */
  coverArt?: (number | null) | Media;
  slug?: string | null;
  /**
   * Auto-synced from the related Release.
   */
  releaseDate?: string | null;
  /**
   * Exact premiere moment — match YouTube Studio scheduled start. Powers the site countdown and release gating. When empty, falls back to release date at UTC midnight.
   */
  premiereAt?: string | null;
  /**
   * Auto-assigned. This song’s position within its composition type, ordered by release date (oldest = 1). Powers the card catalog code, e.g. TSM-2025-ORG-011.
   */
  catalogSequence?: number | null;
  /**
   * Releases whose tracklists already include this song (filtered). Empty until the song is on at least one release—use Link existing or edit the release tracklist.
   */
  relatedReleases?: {
    docs?: (number | Release)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Playlists whose tracklists already include this song (filtered). Empty until linked—use Link existing or open a playlist and add this song under Songs.
   */
  inPlaylists?: {
    docs?: (number | Playlist)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Guest artists. Composed into the ID3 ARTIST (TPE1) frame at sync time as "The Second Messenger feat. [Names]". Leave empty for solo tracks. Album Artist (TPE2) is always "The Second Messenger" regardless.
   */
  featuredArtists?:
    | {
        /**
         * Stage / display name as you want it to read after "feat.".
         */
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The canonical Release this song belongs to for tagging purposes. Drives ALBUM (TALB), TRACK (TRCK), and DISC (TPOS). If the song appears on multiple releases, this is the "original" / authoritative one. Use Tracklist on the Release itself to set track order.
   */
  primaryRelease?: (number | null) | Release;
  /**
   * Updated automatically by the sync job.
   */
  tagSyncStatus?: ('idle' | 'queued' | 'syncing' | 'synced' | 'error') | null;
  /**
   * Timestamp of the last successful tag write.
   */
  tagsSyncedAt?: string | null;
  /**
   * Error message from the most recent failed sync attempt. Cleared on successful sync.
   */
  tagSyncError?: string | null;
  tagsSyncedHash?: string | null;
  /**
   * The canonical MP3 master. This is the file fans get from the free "pay-what-you-want" download. After every save, a background job rewrites its ID3v2.3 tags to match the CMS fields below. See "Tag Sync Status" in the sidebar.
   */
  masterAudio?: (number | null) | Media;
  /**
   * Optional lossless FLAC of the same master. Stored in the Vault (Lieutenant+). Tagged with the same CMS metadata (Vorbis comments) on save.
   */
  masterAudioFlac?: (number | null) | GatedContent;
  /**
   * Optional uncompressed WAV of the same master. Vault archival / Captain-tier download.
   */
  masterAudioWav?: (number | null) | GatedContent;
  /**
   * The 11-character ID (e.g., dQw4w9WgXcQ). Required for the Global Player.
   */
  youtubeId?: string | null;
  /**
   * The song ID (e.g., 5VaIDMKwaYXgELXy6n0ODU). Required for Spotify Saves.
   */
  spotifyId?: string | null;
  streamingLinks?:
    | {
        platform:
          | 'YouTube Music'
          | 'Spotify'
          | 'Tidal'
          | 'Apple Music'
          | 'Amazon Music'
          | 'iHeartRadio'
          | 'Deezer'
          | 'Pandora'
          | 'Qobuz'
          | 'SoundCloud'
          | 'Bandcamp'
          | 'Other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload synchronized files for the deep-dive player.
   */
  stems?:
    | {
        stemName: string;
        audioFile: number | GatedContent;
        volume?: number | null;
        id?: string | null;
      }[]
    | null;
  compositionType:
    | 'Original'
    | 'Cover'
    | 'Public Domain'
    | 'Remix'
    | 'Arrangement'
    | 'Derivative Work'
    | 'Interpolation'
    | 'Mashup'
    | 'Sample'
    | 'Other';
  recordingType: 'Studio' | 'Live' | 'Demo' | 'Other';
  isExplicit?: boolean | null;
  isrc?: string | null;
  /**
   * International Standard Musical Work Code (composition). No native ID3 frame — written as TXXX:ISWC for MP3 and as ISWC Vorbis comment for FLAC.
   */
  iswc?: string | null;
  durationText?: string | null;
  duration?: number | null;
  /**
   * Initial tempo as a whole integer. Drives the TBPM frame. For songs that change tempo, this is the starting BPM; the range is added separately as TXXX:Tempo Range.
   */
  bpm?: number | null;
  bpmEnd?: number | null;
  /**
   * Initial musical key. Long forms like "A# minor" or "Bb major" are normalized to ≤3 chars (`A#m`, `Bb`) before being written to the TKEY frame. Lowercase `m` indicates minor.
   */
  key?: string | null;
  keyEnd?: string | null;
  changesTempo?: boolean | null;
  changesKey?: boolean | null;
  /**
   * For multi-disc releases. Defaults to 1 (almost always correct). Drives the first half of TPOS (e.g. 1/2 for disc 1 of a 2-disc set).
   */
  discNumber?: number | null;
  /**
   * Owner of the master sound recording. Combined with the release year as `℗ {year} {owner}` to form TCOP.
   */
  phonogramCopyrightOwner?: string | null;
  /**
   * Owner of the underlying composition. Combined with year as `© {year} {owner}`. Automatically suppressed for Cover songs (where you do not own the composition).
   */
  compositionCopyrightOwner?: string | null;
  /**
   * Publishing entity. Until a separate publishing company is registered, leave as "Michael Zeta" — it reinforces ownership.
   */
  publisher?: string | null;
  /**
   * Embedded in the file as the USER frame. Most players ignore it, but tag editors will display it.
   */
  termsOfUse?: ('all-rights' | 'cc-attrib-nc' | 'custom') | null;
  /**
   * Free-form usage terms written verbatim to the USER frame.
   */
  termsOfUseCustom?: string | null;
  /**
   * Optional MusicBrainz identifiers. Written to the file as standard MusicBrainz frames (TXXX/UFID for MP3, MUSICBRAINZ_* Vorbis comments for FLAC) so Picard and streaming aggregators recognize the recording. Leave blank until the song is registered on MusicBrainz.
   */
  musicBrainz?: {
    /**
     * The recording (master audio) MBID. Also written to the UFID frame with owner http://musicbrainz.org.
     */
    recordingId?: string | null;
    /**
     * The track MBID specific to the release (MusicBrainz Release Track Id).
     */
    trackId?: string | null;
    releaseId?: string | null;
    releaseGroupId?: string | null;
    artistId?: string | null;
    workId?: string | null;
  };
  /**
   * Used for sorting "Popular" lists. 1000 = Biggest Hit.
   */
  popularity?: number | null;
  /**
   * Broad, record-store-aisle category. Captures wide-net discovery searches like "rock" or "electronic". The first entry is the primary genre written to ID3 TCON; the rest land in GROUPING.
   */
  genres?: (number | Tag)[] | null;
  /**
   * The specific cultural movement or stylistic flavor (Pop-punk, Synthwave, Shoegaze). Captures niche-community searches that operate independently of the broad genre.
   */
  subGenres?: (number | Tag)[] | null;
  /**
   * The use-case or environment where the song is consumed (Workout, Late-night Drive, Vlog Background). High-value for "music for X" long-tail SEO.
   */
  activities?: (number | Tag)[] | null;
  /**
   * What the song is about — the lyrical subject or narrative (Love, Heartbreak, Revenge). Powers conversational "songs about X" queries.
   */
  themes?: (number | Tag)[] | null;
  /**
   * The psychological vibe the song creates for the listener (Energetic, Melancholy, Anthemic). Used for vibe curation and emotional regulation searches.
   */
  moods?: (number | Tag)[] | null;
  /**
   * Audio fidelity and mixing characteristics (Lo-fi, Wall of Sound, Distorted, Warm). Audiophile / texture queries — keep separate from instruments and gear.
   */
  production?: (number | Tag)[] | null;
  /**
   * General musical voices in the arrangement (Electric Guitar, Synthesizer, Male Vocals). Use generic categories — specific models go in Gear.
   */
  instruments?: (number | Tag)[] | null;
  /**
   * Specific hardware, software, DAWs, or instrument models (Fender Stratocaster, Studio One, Boss Katana). Engineer / producer reference-track searches.
   */
  gear?: (number | Tag)[] | null;
  /**
   * Compositional anatomy and structure (Guitar Solo, Instrumental, Odd Time Signature, Vocal Harmonies). For analytical / musician searches.
   */
  arrangements?: (number | Tag)[] | null;
  /**
   * Direct "sounds like" comparisons to other artists, bands, or eras (Blink-182, Early 2000s Era). Powers similar-artist queries; do NOT duplicate as Genres or Sub-genres.
   */
  influences?: (number | Tag)[] | null;
  /**
   * Internal organization and routing tags (Demo, B-Side, Vault Exclusive, Explicit, Work In Progress). Not primary organic-search targets.
   */
  otherTags?: (number | Tag)[] | null;
  credits?:
    | {
        /**
         * Display name (stage name, band name, or known professional name).
         */
        name: string;
        /**
         * Optional. Required for accurate publishing credits — Songwriter credits write the legal name (or fall back to display name) into the COMPOSER (TCOM) frame.
         */
        legalName?: string | null;
        category: 'Songwriter' | 'Performer' | 'Producer/Engineer' | 'Visuals' | 'Special Thanks';
        /**
         * Add multiple roles (e.g. "Guitar", "Backing Vocals")
         */
        roles?:
          | {
              role?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A one or two sentence tagline or "elevator pitch". SoundCloud limits to 140 characters.
   */
  tagline?: string | null;
  /**
   * The full story, sonic details, and lyrics. Supports embeds and images. Typically best to start at H3 since "Liner Notes" section heading is already H2.
   */
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Plain text version for search indexing and quick view. Written to the USLT (Unsynchronized Lyrics) frame in the audio file.
   */
  lyrics?: string | null;
  /**
   * Short message embedded into the file's COMM frame. Defaults to a "thank you" note. Visible to anyone who inspects the file in a tag editor or some media players.
   */
  comment?: string | null;
  /**
   * Files that point to this song from the Gated Content collection.
   */
  linkedGatedContent?: {
    docs?: (number | GatedContent)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  title: string;
  slug?: string | null;
  releaseDate: string;
  type: 'Single' | 'Double' | 'EP' | 'Album' | 'Other';
  distribution?: ('Limited' | 'Global' | 'Exclusive' | 'Other') | null;
  upc?: string | null;
  coverArt: number | Media;
  /**
   * Drag and drop to reorder tracks. The order here drives the TRCK frame written to each track's audio file (track number out of total).
   */
  tracks?: (number | Song)[] | null;
  /**
   * Total number of discs/sides in this release. Defaults to 1. Used as the second half of TPOS (e.g. 1/2 for disc 1 of a 2-disc set).
   */
  discCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  title: string;
  /**
   * Lower numbers appear first in the player. The auto-generated "Discography" always leads, so start your custom playlists at 1+.
   */
  displayOrder?: number | null;
  slug?: string | null;
  description?: string | null;
  coverArt?: (number | null) | Media;
  /**
   * Add and reorder songs. Updates instantly on the site.
   */
  tracks?: (number | Song)[] | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One minimum crew rank per file. Eligible fans can view or play media in the Vault; archives and documents get a download button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gated-content".
 */
export interface GatedContent {
  id: number;
  title: string;
  /**
   * A brief description of the content.
   */
  description?: string | null;
  /**
   * Optional. Link this Vault file to a song. Song pages and the Song editor can surface linked files through this relationship.
   */
  relatedSong?: (number | null) | Song;
  /**
   * Fans at this rank or higher can access the file (Vault + direct file routes). Matches Lieutenant / Commander / Captain Vault clearance in crew rules.
   */
  tierRequired: 'lieutenant' | 'commander' | 'captain';
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  category:
    | 'genre'
    | 'subgenre'
    | 'activity'
    | 'theme'
    | 'mood'
    | 'production'
    | 'instrument'
    | 'gear'
    | 'arrangement'
    | 'influence'
    | 'other';
  slug?: string | null;
  /**
   * Optional. Glyph shown on song cards and the Sonic DNA panel for this tag. Leave empty to use the sensible default for this category (e.g. a guitar tag without an icon falls back to the instrument default).
   */
  icon?:
    | (
        | 'music'
        | 'guitar'
        | 'piano'
        | 'drum'
        | 'bass'
        | 'mic'
        | 'synth'
        | 'headphones'
        | 'keyboard'
        | 'speaker'
        | 'waveform'
        | 'sliders'
        | 'volume'
        | 'radio'
        | 'disc'
        | 'cpu'
        | 'activity'
        | 'dumbbell'
        | 'running'
        | 'car'
        | 'gamepad'
        | 'book'
        | 'code'
        | 'coffee'
        | 'plane'
        | 'party'
        | 'zap'
        | 'heart'
        | 'heart-crack'
        | 'rain'
        | 'flame'
        | 'skull'
        | 'sparkles'
        | 'moon'
        | 'sun'
        | 'sunrise'
        | 'globe'
        | 'swords'
        | 'users'
        | 'user'
        | 'map-pin'
        | 'gift'
        | 'snowflake'
        | 'trees'
        | 'mountain'
        | 'ghost'
        | 'star'
        | 'history'
        | 'crown'
        | 'layers'
        | 'branch'
        | 'repeat'
        | 'clock'
        | 'rocket'
        | 'telescope'
        | 'satellite'
        | 'orbit'
        | 'tag'
      )
    | null;
  /**
   * Optional. Renders above the song grid on /music/tag/<category>/<slug> landing pages. Use to give context for the tag (e.g. why a sub-genre matters, when a particular activity-tag is appropriate). Leave empty for tags that don’t need editorial framing.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Hero image for the /music/tag landing page. If omitted, the page falls back to a stylized header without imagery.
   */
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list".
 */
export interface MailingList {
  id: number;
  email: string;
  source?: ('spotify_presave' | 'newsletter_signup' | 'merch_purchase') | null;
  tags?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presaves".
 */
export interface Presave {
  id: number;
  email: string;
  spotifyId?: string | null;
  refreshToken?: string | null;
  /**
   * When this user followed TSM on Spotify during presave.
   */
  artistFollowedAt?: string | null;
  /**
   * Optional TSM account link for YouTube cron fulfillment (Google refresh token).
   */
  linkedUser?: (number | null) | User;
  /**
   * Per-song platform fulfillment map. Keys are song IDs.
   */
  intentStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  campaigns?: (number | Song)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'songs';
          value: number | Song;
        } | null)
      | ({
          relationTo: 'releases';
          value: number | Release;
        } | null)
      | ({
          relationTo: 'playlists';
          value: number | Playlist;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'songs';
        value: number | Song;
      }
    | {
        relationTo: 'playlists';
        value: number | Playlist;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncAudioTags' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncAudioTags' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'mailing-list';
        value: number | MailingList;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'presaves';
        value: number | Presave;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'gated-content';
        value: number | GatedContent;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mailing-list_select".
 */
export interface MailingListSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature_avif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  title?: T;
  displayOrder?: T;
  slug?: T;
  description?: T;
  coverArt?: T;
  tracks?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presaves_select".
 */
export interface PresavesSelect<T extends boolean = true> {
  email?: T;
  spotifyId?: T;
  refreshToken?: T;
  artistFollowedAt?: T;
  linkedUser?: T;
  intentStatus?: T;
  campaigns?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  releaseDate?: T;
  type?: T;
  distribution?: T;
  upc?: T;
  coverArt?: T;
  tracks?: T;
  discCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  title?: T;
  coverArt?: T;
  slug?: T;
  releaseDate?: T;
  premiereAt?: T;
  catalogSequence?: T;
  relatedReleases?: T;
  inPlaylists?: T;
  featuredArtists?:
    | T
    | {
        name?: T;
        id?: T;
      };
  primaryRelease?: T;
  tagSyncStatus?: T;
  tagsSyncedAt?: T;
  tagSyncError?: T;
  tagsSyncedHash?: T;
  masterAudio?: T;
  masterAudioFlac?: T;
  masterAudioWav?: T;
  youtubeId?: T;
  spotifyId?: T;
  streamingLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  stems?:
    | T
    | {
        stemName?: T;
        audioFile?: T;
        volume?: T;
        id?: T;
      };
  compositionType?: T;
  recordingType?: T;
  isExplicit?: T;
  isrc?: T;
  iswc?: T;
  durationText?: T;
  duration?: T;
  bpm?: T;
  bpmEnd?: T;
  key?: T;
  keyEnd?: T;
  changesTempo?: T;
  changesKey?: T;
  discNumber?: T;
  phonogramCopyrightOwner?: T;
  compositionCopyrightOwner?: T;
  publisher?: T;
  termsOfUse?: T;
  termsOfUseCustom?: T;
  musicBrainz?:
    | T
    | {
        recordingId?: T;
        trackId?: T;
        releaseId?: T;
        releaseGroupId?: T;
        artistId?: T;
        workId?: T;
      };
  popularity?: T;
  genres?: T;
  subGenres?: T;
  activities?: T;
  themes?: T;
  moods?: T;
  production?: T;
  instruments?: T;
  gear?: T;
  arrangements?: T;
  influences?: T;
  otherTags?: T;
  credits?:
    | T
    | {
        name?: T;
        legalName?: T;
        category?: T;
        roles?:
          | T
          | {
              role?: T;
              id?: T;
            };
        id?: T;
      };
  tagline?: T;
  about?: T;
  lyrics?: T;
  comment?: T;
  linkedGatedContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gated-content_select".
 */
export interface GatedContentSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  relatedSong?: T;
  tierRequired?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  slug?: T;
  icon?: T;
  description?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  displayNameFormat?: T;
  displayName?: T;
  avatar?: T;
  bio?: T;
  favoriteSong?: T;
  zipCode?: T;
  birthdate?: T;
  gender?: T;
  themePreference?: T;
  notificationSettings?:
    | T
    | {
        newsletter?: T;
        productUpdates?: T;
        accountActivity?: T;
      };
  role?: T;
  crewRank?: T;
  stripeCustomerId?: T;
  youtubeConnected?: T;
  googleAccessToken?: T;
  googleRefreshToken?: T;
  googleTokenExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide presentation settings, including the featured theme that rotates with releases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Default color theme for visitors who have not picked their own. Flip this on release day to refresh the whole site — anyone "following the featured theme" updates automatically.
   */
  defaultTheme: 'dark' | 'light' | 'interstellar' | 'kelly_come_home' | 'nebula' | 'distress';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultTheme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncAudioTags".
 */
export interface TaskSyncAudioTags {
  input: {
    /**
     * ID of the Song whose master audio should be re-tagged.
     */
    songId: number;
  };
  output: {
    status?: string | null;
    detail?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?:
    | ('typescript' | 'javascript' | 'css' | 'html' | 'json' | 'yaml' | 'sql' | 'markdown' | 'shell' | 'python')
    | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  /**
   * Paste the full iframe embed code (e.g. from SoundCloud, YouTube, Spotify). Only standard iframes are supported.
   */
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'posts';
            value: number | Post;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'ghost' | 'destructive' | 'secondary' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneQuarter' | 'oneThird' | 'half' | 'twoThirds' | 'threeQuarters' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'posts';
            value: number | Post;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}