import {
  type MigrateUpArgs,
  type MigrateDownArgs,
  sql,
} from '@payloadcms/db-vercel-postgres'

/**
 * Remap existing `tags` documents to the 11-layer Sonic Tag Ontology
 * (see `.cursor/rules/sonic-tag-ontology.mdc`).
 *
 * This migration is the data half of the ontology refactor. The schema half
 * (enum value adds + new `songs_rels.path` allow-list) is generated by
 * `pnpm migrate:create rename-style-add-eleven-categories` and runs first
 * because its filename uses a real-time timestamp (this file uses
 * `9999999999999` to sort last).
 *
 * Steps performed:
 *   1. For each (name, oldCategory) row in REMAP, update the tag's category
 *      to the new value. If a tag with the SAME name already exists in the
 *      destination category (collision), we MERGE: re-point every
 *      `songs_rels` row from the source tag id to the target tag id, then
 *      delete the now-empty source tag.
 *   2. Fix the "Fender Statocaster" -> "Fender Stratocaster" typo at the
 *      same time as moving it to the `gear` category.
 *   3. Rename `songs_rels.path` rows from `styles` -> `subGenres` so song
 *      relationships pointed at the renamed Songs.ts field continue to
 *      resolve.
 *   4. Safety net: any leftover `tags.category = 'style'` rows that were
 *      added between this migration being authored and run get folded into
 *      the closest semantic match (`subgenre`).
 *
 * Down migration reverses the category mapping. It does NOT undo merges or
 * the typo fix (impossible without remembering the prior id assignments)
 * and does NOT recreate orphaned source tags — both are documented as
 * lossy. If you need pristine rollback, restore from a DB snapshot taken
 * before applying this migration.
 */

type OldCategory =
  | 'genre'
  | 'style'
  | 'mood'
  | 'production'
  | 'theme'
  | 'instrument'
  | 'arrangement'
  | 'other'

type NewCategory =
  | 'genre'
  | 'subgenre'
  | 'activity'
  | 'theme'
  | 'mood'
  | 'production'
  | 'instrument'
  | 'gear'
  | 'arrangement'
  | 'influence'
  | 'other'

type RemapEntry = {
  /** Current `tags.name` to look up. Match is exact (case-sensitive). */
  name: string
  /** Current category of the existing tag. Required for disambiguation
   *  (e.g. "Dark" exists in both `mood` and `production`). */
  from: OldCategory
  /** Target category in the new ontology. */
  to: NewCategory
  /** Optional new name. Used for typo fixes (e.g. Statocaster -> Stratocaster). */
  rename?: string
}

/**
 * Source of truth: `.cursor/sonic-tags-case/Table of Tags (End).md`.
 * Only entries where `from !== to` (or where a rename is needed) need to
 * be listed here — same-category rows are no-ops.
 */
const REMAP: RemapEntry[] = [
  // ---- Old "Genre" rows that move to "Sub-genre" ----
  { name: 'Soft Rock', from: 'genre', to: 'subgenre' },
  { name: 'Punk', from: 'genre', to: 'subgenre' },
  { name: 'Pop-punk', from: 'genre', to: 'subgenre' },
  { name: 'Alternative', from: 'genre', to: 'subgenre' },
  { name: 'Hard Rock', from: 'genre', to: 'subgenre' },
  { name: 'Pop / Rock', from: 'genre', to: 'subgenre' },

  // ---- Old "Style" rows scattered across new categories ----
  { name: 'Tribute', from: 'style', to: 'other' },
  { name: 'Lo-Fi', from: 'style', to: 'production' },
  { name: 'Western', from: 'style', to: 'subgenre' },
  { name: 'Virtuoso', from: 'style', to: 'arrangement' },
  { name: 'Party', from: 'style', to: 'activity' },
  { name: 'Intellectual', from: 'style', to: 'mood' },
  { name: 'Comedy / Humor / Funny', from: 'style', to: 'theme' },
  { name: 'Christmas', from: 'style', to: 'theme' },
  { name: 'Instrumental', from: 'style', to: 'arrangement' },
  { name: 'A Cappella', from: 'style', to: 'arrangement' },
  { name: 'Holiday', from: 'style', to: 'theme' },
  { name: 'Lyrical', from: 'style', to: 'arrangement' },
  { name: 'Dance', from: 'style', to: 'activity' },

  // ---- Old "Mood" rows that better fit Themes ----
  { name: 'Pain', from: 'mood', to: 'theme' },
  { name: 'Journey / Quest', from: 'mood', to: 'theme' },
  { name: 'Grief', from: 'mood', to: 'theme' },

  // ---- Old "Production" rows that aren't really production ----
  { name: 'Fighting', from: 'production', to: 'theme' },
  { name: 'Dynamic', from: 'production', to: 'arrangement' },
  { name: 'Deep Bass', from: 'production', to: 'instrument' },

  // ---- Old "Instrument" rows that are really gear or arrangement ----
  { name: 'Orchestral', from: 'instrument', to: 'arrangement' },
  // Typo fix bundled with category move
  {
    name: 'Fender Statocaster',
    from: 'instrument',
    to: 'gear',
    rename: 'Fender Stratocaster',
  },
  {
    name: 'Presonus Studio One / Fender Studio Pro',
    from: 'instrument',
    to: 'gear',
  },
  { name: 'Ibanez S61 Axion', from: 'instrument', to: 'gear' },
  { name: 'Boss Katana', from: 'instrument', to: 'gear' },
  { name: 'Vocal Harmonies', from: 'instrument', to: 'arrangement' },
]

/**
 * Reverse mapping for `down()`. Same name; flip `from` and `to`.
 * Lossy: collisions and renames cannot be perfectly undone (see header).
 */
const REVERSE_REMAP: RemapEntry[] = REMAP.map((entry) => ({
  name: entry.rename ?? entry.name,
  from: entry.to as unknown as OldCategory,
  to: entry.from as unknown as NewCategory,
  rename: entry.rename ? entry.name : undefined,
}))

type TagRow = { id: number; name: string; category: string }

/**
 * Look up a tag by exact (name, category) pair. Returns null if absent.
 */
async function findTag(
  db: MigrateUpArgs['db'],
  name: string,
  category: string,
): Promise<TagRow | null> {
  const result = await db.execute(sql`
    SELECT id, name, category
    FROM tags
    WHERE name = ${name} AND category = ${category}
    LIMIT 1
  `)
  const row = (result.rows?.[0] ?? null) as TagRow | null
  return row
}

/**
 * Re-point every `songs_rels` row from sourceTagId to targetTagId, then
 * delete the source tag. Used when (newName, newCategory) already exists.
 */
async function mergeTags(
  db: MigrateUpArgs['db'],
  payload: MigrateUpArgs['payload'],
  sourceId: number,
  targetId: number,
  context: string,
): Promise<void> {
  payload.logger.info(
    `🏷️  [tag-remap] MERGE ${context}: re-pointing relations ${sourceId} -> ${targetId}`,
  )

  // Re-point every reference in songs_rels.
  await db.execute(sql`
    UPDATE songs_rels
    SET tags_id = ${targetId}
    WHERE tags_id = ${sourceId}
  `)

  // Drop duplicate (parent_id, path, tags_id) rows that the merge can create.
  // Postgres does not have a single-statement deduplicate, so we use ctid.
  await db.execute(sql`
    DELETE FROM songs_rels a
    USING songs_rels b
    WHERE a.ctid < b.ctid
      AND a.parent_id IS NOT DISTINCT FROM b.parent_id
      AND a.path IS NOT DISTINCT FROM b.path
      AND a.tags_id IS NOT DISTINCT FROM b.tags_id
  `)

  // Now safe to remove the orphaned source tag.
  await db.execute(sql`DELETE FROM tags WHERE id = ${sourceId}`)
}

async function applyRemap(
  args: MigrateUpArgs,
  entries: RemapEntry[],
): Promise<void> {
  const { db, payload } = args

  for (const entry of entries) {
    const source = await findTag(db, entry.name, entry.from)
    if (!source) continue // Already migrated, never existed, or pre-merged.

    const newName = entry.rename ?? entry.name
    const collision = await findTag(db, newName, entry.to)

    if (collision && collision.id !== source.id) {
      // A tag with the destination identity already exists — merge into it.
      await mergeTags(
        db,
        payload,
        source.id,
        collision.id,
        `${entry.name}@${entry.from} -> ${newName}@${entry.to}`,
      )
      continue
    }

    // No collision: update category (and name if a rename was requested).
    if (entry.rename) {
      await db.execute(sql`
        UPDATE tags
        SET category = ${entry.to}, name = ${entry.rename}
        WHERE id = ${source.id}
      `)
      payload.logger.info(
        `🏷️  [tag-remap] RENAME+MOVE "${entry.name}"@${entry.from} -> "${entry.rename}"@${entry.to}`,
      )
    } else {
      await db.execute(sql`
        UPDATE tags
        SET category = ${entry.to}
        WHERE id = ${source.id}
      `)
      payload.logger.info(
        `🏷️  [tag-remap] MOVE "${entry.name}"@${entry.from} -> @${entry.to}`,
      )
    }
  }
}

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  payload.logger.info(
    '🏷️  [tag-remap] up() starting — applying 11-layer ontology remap',
  )

  // 1) Per-name remap from the table. Handles all known intentional moves,
  //    the Fender Stratocaster typo fix, and merges on collision.
  await applyRemap({ db, payload, req }, REMAP)

  // 2) Rename songs_rels.path 'styles' -> 'subGenres'. Payload's auto-gen
  //    schema migration only updates type/structure, never relationship-name
  //    string data, so this is on us.
  const stylesPathRes = await db.execute(sql`
    UPDATE songs_rels
    SET path = 'subGenres'
    WHERE path = 'styles'
  `)
  payload.logger.info(
    `🏷️  [tag-remap] songs_rels.path 'styles' -> 'subGenres' (rows updated: ${stylesPathRes.rowCount ?? 0})`,
  )

  // 3) Safety net: any straggler tags still in the legacy 'style' bucket
  //    (e.g. created in admin between this migration being authored and run)
  //    fall through to the closest semantic match — sub-genre.
  const stragglerRes = await db.execute(sql`
    UPDATE tags
    SET category = 'subgenre'
    WHERE category = 'style'
  `)
  if ((stragglerRes.rowCount ?? 0) > 0) {
    payload.logger.warn(
      `🏷️  [tag-remap] Caught ${stragglerRes.rowCount} stray 'style' tag(s) and folded them into 'subgenre'. Review the admin if any belonged elsewhere.`,
    )
  }

  payload.logger.info('🏷️  [tag-remap] up() complete')
}

export async function down({
  db,
  payload,
  req,
}: MigrateDownArgs): Promise<void> {
  payload.logger.info(
    '🏷️  [tag-remap] down() starting — reverting ontology remap (lossy)',
  )

  // 1) Reverse the songs_rels.path rename first so when we flip categories
  //    back any field-name lookups still resolve.
  await db.execute(sql`
    UPDATE songs_rels
    SET path = 'styles'
    WHERE path = 'subGenres'
  `)

  // 2) Reverse the per-name moves. Merges and the typo fix are not perfectly
  //    reversible — see header comment.
  await applyRemap({ db, payload, req }, REVERSE_REMAP)

  payload.logger.info('🏷️  [tag-remap] down() complete')
}
